import { describe, expect, it } from "vitest";
import { safeForumAvatarPath, safeForumMessagePath, safeForumTopicPath } from "./forum-paths";

describe("Discourse relative path guards", () => {
  it("accepts only allowlisted same-origin paths", () => {
    // Given: valid Discourse paths generated by the Profile server.
    const avatar = "/letter_avatar/tx_example/2/120.png";
    const topic = "/t/safe-topic/42/3";
    const message = "/new-message?username=tx_abcdefghijklmnop";

    // When: each path crosses the browser boundary.
    // Then: each allowlisted relative path remains usable.
    expect(safeForumAvatarPath(avatar)).toBe(avatar);
    expect(safeForumTopicPath(topic)).toBe(topic);
    expect(safeForumMessagePath(message)).toBe(message);
  });

  it("rejects external, traversal, and malformed paths", () => {
    // Given: paths that could leave the same-origin Discourse mount.
    const unsafePaths = ["https://outside.example/avatar.png", "//outside.example/x", "/t/../admin", "/new-message?username=other"];

    // When: each path crosses the browser boundary.
    const guarded = unsafePaths.map((path) => [
      safeForumAvatarPath(path),
      safeForumTopicPath(path),
      safeForumMessagePath(path),
    ]);

    // Then: no unsafe value survives any path guard.
    expect(guarded.flat()).toEqual(Array.from({ length: 12 }, () => null));
  });
});
