export const APP_ROUTE_PATHS = [
  "/",
  "/demo",
  "/studio",
  "/members/:memberId",
  "/members/new",
  "/test-run",
  "/test-run/:runId",
  "/versions",
  "/activity",
  "/forum",
  "/leaderboard",
  "/me",
  "/me/settings",
  "/me/contacts",
  "/captains/:publicId",
  "/arena",
  "/arena/challenges/:challengeVersionId",
  "/arena/runs/:runId",
  "/arena/runs/:runId/result",
] as const;
